/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "nanto.io/application-auto-scaling-service/pkg/k8sclient/apis/autoscaling/v1alpha1"
)

// FakeCustomedHorizontalPodAutoscalers implements CustomedHorizontalPodAutoscalerInterface
type FakeCustomedHorizontalPodAutoscalers struct {
	Fake *FakeAutoscalingV1alpha1
	ns   string
}

var customedhorizontalpodautoscalersResource = schema.GroupVersionResource{Group: "autoscaling.cce.io", Version: "v1alpha1", Resource: "customedhorizontalpodautoscalers"}

var customedhorizontalpodautoscalersKind = schema.GroupVersionKind{Group: "autoscaling.cce.io", Version: "v1alpha1", Kind: "CustomedHorizontalPodAutoscaler"}

// Get takes name of the customedHorizontalPodAutoscaler, and returns the corresponding customedHorizontalPodAutoscaler object, and an error if there is any.
func (c *FakeCustomedHorizontalPodAutoscalers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CustomedHorizontalPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(customedhorizontalpodautoscalersResource, c.ns, name), &v1alpha1.CustomedHorizontalPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomedHorizontalPodAutoscaler), err
}

// List takes label and field selectors, and returns the list of CustomedHorizontalPodAutoscalers that match those selectors.
func (c *FakeCustomedHorizontalPodAutoscalers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CustomedHorizontalPodAutoscalerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(customedhorizontalpodautoscalersResource, customedhorizontalpodautoscalersKind, c.ns, opts), &v1alpha1.CustomedHorizontalPodAutoscalerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CustomedHorizontalPodAutoscalerList{ListMeta: obj.(*v1alpha1.CustomedHorizontalPodAutoscalerList).ListMeta}
	for _, item := range obj.(*v1alpha1.CustomedHorizontalPodAutoscalerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customedHorizontalPodAutoscalers.
func (c *FakeCustomedHorizontalPodAutoscalers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(customedhorizontalpodautoscalersResource, c.ns, opts))

}

// Create takes the representation of a customedHorizontalPodAutoscaler and creates it.  Returns the server's representation of the customedHorizontalPodAutoscaler, and an error, if there is any.
func (c *FakeCustomedHorizontalPodAutoscalers) Create(ctx context.Context, customedHorizontalPodAutoscaler *v1alpha1.CustomedHorizontalPodAutoscaler, opts v1.CreateOptions) (result *v1alpha1.CustomedHorizontalPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(customedhorizontalpodautoscalersResource, c.ns, customedHorizontalPodAutoscaler), &v1alpha1.CustomedHorizontalPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomedHorizontalPodAutoscaler), err
}

// Update takes the representation of a customedHorizontalPodAutoscaler and updates it. Returns the server's representation of the customedHorizontalPodAutoscaler, and an error, if there is any.
func (c *FakeCustomedHorizontalPodAutoscalers) Update(ctx context.Context, customedHorizontalPodAutoscaler *v1alpha1.CustomedHorizontalPodAutoscaler, opts v1.UpdateOptions) (result *v1alpha1.CustomedHorizontalPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(customedhorizontalpodautoscalersResource, c.ns, customedHorizontalPodAutoscaler), &v1alpha1.CustomedHorizontalPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomedHorizontalPodAutoscaler), err
}

// Delete takes name of the customedHorizontalPodAutoscaler and deletes it. Returns an error if one occurs.
func (c *FakeCustomedHorizontalPodAutoscalers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(customedhorizontalpodautoscalersResource, c.ns, name), &v1alpha1.CustomedHorizontalPodAutoscaler{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomedHorizontalPodAutoscalers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(customedhorizontalpodautoscalersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CustomedHorizontalPodAutoscalerList{})
	return err
}

// Patch applies the patch and returns the patched customedHorizontalPodAutoscaler.
func (c *FakeCustomedHorizontalPodAutoscalers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CustomedHorizontalPodAutoscaler, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(customedhorizontalpodautoscalersResource, c.ns, name, pt, data, subresources...), &v1alpha1.CustomedHorizontalPodAutoscaler{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CustomedHorizontalPodAutoscaler), err
}
