/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1 "nanto.io/application-auto-scaling-service/pkg/apis/batch/v1"
	scheme "nanto.io/application-auto-scaling-service/pkg/client/clientset/versioned/scheme"
)

// ForecastTasksGetter has a method to return a ForecastTaskInterface.
// A group's client should implement this interface.
type ForecastTasksGetter interface {
	ForecastTasks(namespace string) ForecastTaskInterface
}

// ForecastTaskInterface has methods to work with ForecastTask resources.
type ForecastTaskInterface interface {
	Create(ctx context.Context, forecastTask *v1.ForecastTask, opts metav1.CreateOptions) (*v1.ForecastTask, error)
	Update(ctx context.Context, forecastTask *v1.ForecastTask, opts metav1.UpdateOptions) (*v1.ForecastTask, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ForecastTask, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ForecastTaskList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ForecastTask, err error)
	ForecastTaskExpansion
}

// forecastTasks implements ForecastTaskInterface
type forecastTasks struct {
	client rest.Interface
	ns     string
}

// newForecastTasks returns a ForecastTasks
func newForecastTasks(c *BatchV1Client, namespace string) *forecastTasks {
	return &forecastTasks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the forecastTask, and returns the corresponding forecastTask object, and an error if there is any.
func (c *forecastTasks) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ForecastTask, err error) {
	result = &v1.ForecastTask{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("forecasttasks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ForecastTasks that match those selectors.
func (c *forecastTasks) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ForecastTaskList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ForecastTaskList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("forecasttasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested forecastTasks.
func (c *forecastTasks) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("forecasttasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a forecastTask and creates it.  Returns the server's representation of the forecastTask, and an error, if there is any.
func (c *forecastTasks) Create(ctx context.Context, forecastTask *v1.ForecastTask, opts metav1.CreateOptions) (result *v1.ForecastTask, err error) {
	result = &v1.ForecastTask{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("forecasttasks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(forecastTask).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a forecastTask and updates it. Returns the server's representation of the forecastTask, and an error, if there is any.
func (c *forecastTasks) Update(ctx context.Context, forecastTask *v1.ForecastTask, opts metav1.UpdateOptions) (result *v1.ForecastTask, err error) {
	result = &v1.ForecastTask{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("forecasttasks").
		Name(forecastTask.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(forecastTask).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the forecastTask and deletes it. Returns an error if one occurs.
func (c *forecastTasks) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("forecasttasks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *forecastTasks) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("forecasttasks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched forecastTask.
func (c *forecastTasks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ForecastTask, err error) {
	result = &v1.ForecastTask{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("forecasttasks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
