/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	batchv1 "nanto.io/application-auto-scaling-service/pkg/apis/batch/v1"
)

// FakeForecastTasks implements ForecastTaskInterface
type FakeForecastTasks struct {
	Fake *FakeBatchV1
	ns   string
}

var forecasttasksResource = schema.GroupVersionResource{Group: "batch.nanto.io", Version: "v1", Resource: "forecasttasks"}

var forecasttasksKind = schema.GroupVersionKind{Group: "batch.nanto.io", Version: "v1", Kind: "ForecastTask"}

// Get takes name of the forecastTask, and returns the corresponding forecastTask object, and an error if there is any.
func (c *FakeForecastTasks) Get(ctx context.Context, name string, options v1.GetOptions) (result *batchv1.ForecastTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(forecasttasksResource, c.ns, name), &batchv1.ForecastTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*batchv1.ForecastTask), err
}

// List takes label and field selectors, and returns the list of ForecastTasks that match those selectors.
func (c *FakeForecastTasks) List(ctx context.Context, opts v1.ListOptions) (result *batchv1.ForecastTaskList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(forecasttasksResource, forecasttasksKind, c.ns, opts), &batchv1.ForecastTaskList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &batchv1.ForecastTaskList{ListMeta: obj.(*batchv1.ForecastTaskList).ListMeta}
	for _, item := range obj.(*batchv1.ForecastTaskList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested forecastTasks.
func (c *FakeForecastTasks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(forecasttasksResource, c.ns, opts))

}

// Create takes the representation of a forecastTask and creates it.  Returns the server's representation of the forecastTask, and an error, if there is any.
func (c *FakeForecastTasks) Create(ctx context.Context, forecastTask *batchv1.ForecastTask, opts v1.CreateOptions) (result *batchv1.ForecastTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(forecasttasksResource, c.ns, forecastTask), &batchv1.ForecastTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*batchv1.ForecastTask), err
}

// Update takes the representation of a forecastTask and updates it. Returns the server's representation of the forecastTask, and an error, if there is any.
func (c *FakeForecastTasks) Update(ctx context.Context, forecastTask *batchv1.ForecastTask, opts v1.UpdateOptions) (result *batchv1.ForecastTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(forecasttasksResource, c.ns, forecastTask), &batchv1.ForecastTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*batchv1.ForecastTask), err
}

// Delete takes name of the forecastTask and deletes it. Returns an error if one occurs.
func (c *FakeForecastTasks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(forecasttasksResource, c.ns, name), &batchv1.ForecastTask{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeForecastTasks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(forecasttasksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &batchv1.ForecastTaskList{})
	return err
}

// Patch applies the patch and returns the patched forecastTask.
func (c *FakeForecastTasks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *batchv1.ForecastTask, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(forecasttasksResource, c.ns, name, pt, data, subresources...), &batchv1.ForecastTask{})

	if obj == nil {
		return nil, err
	}
	return obj.(*batchv1.ForecastTask), err
}
